trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: targetEnv
  displayName: "Target Environment"
  type: string
  default: "dev"
  values:
  - dev
  - prod

- name: pbixPath
  displayName: "Path to PBIX Report"
  type: string
  default: "Demo Report"  # Just the folder name, script will handle the rest

stages:
- stage: Deploy
  displayName: "Deploy PBIX Report"
  jobs:
  - job: DeployJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    # Ensure .NET SDK available for installing/running pbi-tools
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
      displayName: 'Install .NET SDK'

    - script: |
        pip install requests psutil
      displayName: 'Install Python dependencies'

    - script: |
        dotnet tool install -g PbiTools || echo "pbi-tools already installed"
        echo "##vso[task.prependpath]$HOME/.dotnet/tools"
        export PATH="$HOME/.dotnet/tools:$PATH"
        pbi-tools --version || true
      displayName: 'Install pbi-tools'

    # Add debugging to see what files exist
    - script: |
        echo "Repository contents:"
        ls -la "$(Build.SourcesDirectory)/"
        echo ""
        echo "Demo Report folder contents:"
        ls -la "$(Build.SourcesDirectory)/Demo Report/" || echo "Demo Report folder not found"
      displayName: 'Debug - List repository contents'

    - script: |
        which pbi-tools || (echo "pbi-tools not found in PATH" && exit 1)
        pbi-tools build "$(Build.SourcesDirectory)/${{ parameters.pbixPath }}" --out "$(Build.ArtifactStagingDirectory)/report.pbix"
        echo "Built PBIX size:" && ls -lh "$(Build.ArtifactStagingDirectory)/report.pbix"
      displayName: 'Build PBIX with pbi-tools'

    - script: |
        which pbi-tools || echo "pbi-tools not found in PATH, using already-built PBIX"
        python scripts/main.py --env ${{ parameters.targetEnv }} --pbix "$(Build.ArtifactStagingDirectory)/report.pbix"
      displayName: 'Deploy PBIX Report'