trigger: none

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build the project"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
      
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: |
          python main.py
        displayName: "Run main orchestrator"

- stage: DeployDev
  displayName: "Deploy to Dev"
  dependsOn: Build
  jobs:
  - deployment: DeployDevJob
    displayName: "Deploy to Dev Environment"
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying to Dev Environment"
              displayName: "Deploy step"

- stage: DeployProd
  displayName: "Deploy to Prod"
  dependsOn: DeployDev
  jobs:
  - deployment: DeployProdJob
    displayName: "Deploy to Prod Environment"
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying to Prod Environment"
              displayName: "Deploy step"
