trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: targetEnv
  displayName: "Target Environment"
  type: string
  default: "dev"
  values:
  - dev
  - prod

- name: pbipPath
  displayName: "Path to PBIP Report"
  type: string
  default: "Demo Report/Demo Report.pbip"  # Corrected path

stages:
- stage: Deploy
  displayName: "Deploy PBIP Report"
  jobs:
  - job: DeployJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    - script: |
        pip install requests
      displayName: 'Install dependencies'

    - script: |
        python scripts/main.py --env ${{ parameters.targetEnv }} --pbip "$(Build.SourcesDirectory)/${{ parameters.pbipPath }}"
      displayName: 'Deploy PBIP Report'